{% set version = "6.9.2" %}

package:
  name: qt
  version: {{ version }}

build:
  number: 0
  # https://doc.qt.io/qt-6/qt-releases.html#binary-compatibility
  run_exports:
    - {{ pin_subpackage('qt', max_pin='x.x') }}

requirements:
  host:
    - qt-main {{ version }}
    - qtwebengine {{ version }}

{% set qt_libs = [
  # QtWebEngine
  "Pdf",
  "PdfQuick",
  "PdfWidgets",
  "WebEngineCore",
  "WebEngineQuick",
  "WebEngineQuickDelegatesQml",
  "WebEngineWidgets"
] %}

test:
  requires:
    - pkg-config
  commands:
{% for lib_name in qt_libs %}
    - pkg-config --exists --print-errors "Qt6{{ lib_name }} >= {{ version }} Qt6{{ lib_name }} < {{ version[0] }}.{{ version.split(".")[1] | int + 1 }}"  # [unix]
{% endfor %}

about:
  home: https://www.qt.io
  license: LGPL-3.0-only
  license_file: LICENSE.LGPLv3
  license_family: LGPL
  summary: 'Qt is a cross-platform application and UI framework.'
  description: |
    Qt helps you create connected devices, UIs & applications that run
    anywhere on any device, on any operating system at any time.
  doc_url: https://doc.qt.io/
  dev_url: https://github.com/qt

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - duncanmmacleod
    - gillins
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
    - Tobias-Fischer
